import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from '@/app/components/ui/Navbar/page';
import "./globals.css";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        {/* 🔹 Navbar no topo */}
        <Navbar />

        {/* 🔹 Conteúdo principal ocupa todo o espaço disponível */}
        <main className="flex-grow">{children}</main>

        {/* 🔹 Footer sempre no final */}
        <Footer />
      </body>
    </html>
  );
}
